import { Roadmap, PDFResource, Problem, CommunityPost } from '@/types';

export const mockRoadmaps: Roadmap[] = [
  {
    id: '1',
    title: 'Frontend Developer',
    description: 'Master modern frontend technologies including React, Vue, and advanced CSS',
    category: 'Web Development',
    difficulty: 'beginner',
    status: 'In Progress',
    progress: 65,
    skills: [
      {
        id: '1',
        title: 'HTML & CSS Fundamentals',
        description: 'Learn the basics of HTML and CSS',
        weeks: 2,
        difficulty: 'beginner',
        resources: ['HTML Guide', 'CSS Tutorial'],
        projects: ['Personal Portfolio'],
        estimatedHours: 20,
        completed: true,
        current: false
      }
    ],
    estimatedHours: 480,
    demand: 'High',
    createdAt: '2024-01-01T00:00:00Z',
    updatedAt: '2024-01-15T00:00:00Z'
  },
  {
    id: '2',
    title: 'Backend Developer',
    description: 'Learn server-side development with Node.js, Python, databases, and APIs',
    category: 'Web Development',
    difficulty: 'intermediate',
    status: 'Not Started',
    progress: 0,
    skills: [],
    estimatedHours: 600,
    demand: 'High',
    createdAt: '2024-01-01T00:00:00Z',
    updatedAt: '2024-01-01T00:00:00Z'
  },
  {
    id: '3',
    title: 'Full Stack Developer',
    description: 'Complete path covering both frontend and backend development skills',
    category: 'Web Development',
    difficulty: 'advanced',
    modules: 20,
    estimatedTime: '6-8 months',
    color: 'from-blue-500 to-purple-500',
    icon: 'fas fa-layer-group',
    progress: 0,
  },
  {
    id: '4',
    title: 'Data Science',
    description: 'Master Python, machine learning, data analysis, and visualization tools',
    category: 'Data Science',
    difficulty: 'intermediate',
    modules: 18,
    estimatedTime: '5-6 months',
    color: 'from-pink-500 to-rose-500',
    icon: 'fas fa-chart-bar',
    progress: 0,
  },
  {
    id: '5',
    title: 'Mobile Development',
    description: 'Build mobile apps with React Native, Flutter, and native iOS/Android',
    category: 'Mobile Development',
    difficulty: 'intermediate',
    modules: 14,
    estimatedTime: '4-5 months',
    color: 'from-indigo-500 to-blue-500',
    icon: 'fas fa-mobile-alt',
    progress: 0,
  },
  {
    id: '6',
    title: 'DevOps Engineer',
    description: 'Learn CI/CD, Docker, Kubernetes, cloud platforms, and automation tools',
    category: 'DevOps',
    difficulty: 'advanced',
    modules: 16,
    estimatedTime: '5-6 months',
    color: 'from-yellow-500 to-orange-500',
    icon: 'fas fa-cogs',
    progress: 0,
  },
];

export const mockPdfResources: PDFResource[] = [
  {
    id: '1',
    title: 'JavaScript Fundamentals Handbook',
    description: 'A comprehensive guide to JavaScript basics including variables, functions, and objects',
    category: 'javascript',
    difficulty: 'beginner',
    pages: 42,
    size: '2.4 MB',
    downloads: 1245,
    uploadDate: '2024-01-15',
    tags: ['beginner', 'fundamentals'],
  },
  {
    id: '2',
    title: 'React Hooks Explained',
    description: 'Deep dive into React hooks with practical examples and best practices',
    category: 'react',
    difficulty: 'intermediate',
    pages: 36,
    size: '1.8 MB',
    downloads: 887,
    uploadDate: '2024-01-20',
    tags: ['intermediate', 'hooks'],
  },
  {
    id: '3',
    title: 'CSS Grid and Flexbox Mastery',
    description: 'Master modern CSS layout techniques with detailed examples',
    category: 'css',
    difficulty: 'intermediate',
    pages: 28,
    size: '3.2 MB',
    downloads: 756,
    tags: ['intermediate', 'layout'],
    addedDate: '2024-01-10T00:00:00Z',
  },
  {
    id: '4',
    title: 'Building RESTful APIs with Node.js',
    description: 'Learn to create robust APIs using Node.js, Express, and MongoDB',
    category: 'nodejs',
    difficulty: 'advanced',
    pages: 54,
    size: '4.1 MB',
    downloads: 632,
    tags: ['advanced', 'backend'],
    addedDate: '2024-01-22T00:00:00Z',
  },
  {
    id: '5',
    title: 'TypeScript for React Developers',
    description: 'Practical guide to using TypeScript with React for type-safe applications',
    category: 'typescript',
    difficulty: 'intermediate',
    pages: 48,
    size: '2.7 MB',
    downloads: 543,
    tags: ['intermediate', 'types'],
    addedDate: '2024-01-25T00:00:00Z',
  },
  {
    id: '6',
    title: 'HTML5 Semantic Elements Guide',
    description: 'Comprehensive guide to semantic HTML for better accessibility and SEO',
    category: 'html',
    difficulty: 'beginner',
    pages: 32,
    size: '1.5 MB',
    downloads: 421,
    tags: ['beginner', 'accessibility'],
    addedDate: '2024-01-23T00:00:00Z',
  },
];

export const mockProblems: Problem[] = [
  {
    id: '1',
    title: 'Two Sum',
    description: 'Given an array of integers and a target sum, return indices of two numbers that add up to the target.',
    difficulty: 'easy',
    category: 'Arrays',
    tags: ['Array', 'Hash Table'],
    xpReward: 100,
    completed: false,
    attempts: 0
  },
  {
    id: '2',
    title: 'Valid Parentheses',
    description: 'Determine if the input string has valid parentheses combinations.',
    difficulty: 'easy',
    category: 'Strings',
    tags: ['Stack', 'Strings'],
    xpReward: 150,
    completed: false,
    attempts: 0
  },
  {
    id: '3',
    title: 'Maximum Subarray',
    description: 'Find the contiguous subarray with the largest sum.',
    difficulty: 'medium',
    category: 'Dynamic Programming',
    tags: ['Dynamic Programming', 'Arrays'],
    xpReward: 250,
    completed: true,
    attempts: 2
  },
  {
    id: '4',
    title: 'Binary Tree Traversal',
    description: 'Implement different binary tree traversal algorithms.',
    difficulty: 'hard',
    category: 'Trees',
    tags: ['Trees', 'Recursion'],
    xpReward: 400,
    completed: false,
    attempts: 0
  },
  {
    id: '5',
    title: 'Reverse String',
    description: 'Write a function that reverses a string using different approaches.',
    difficulty: 'easy',
    category: 'Strings',
    tags: ['Strings', 'Two Pointers'],
    xpReward: 100,
    completed: true,
    attempts: 1
  },
];

export const mockCommunityPosts: CommunityPost[] = [
  {
    id: '1',
    title: 'Best practices for React state management',
    category: 'React',
    tags: ['React', 'State Management'],
    createdAt: '2024-01-20T00:00:00Z',
    content: 'What are your favorite patterns for managing state in React applications?',
    replies: 15,
    userId: 'user1',
    likes: 42,
    isResolved: false
  },
  {
    id: '2',
    author: {
      name: 'Maria Johnson',
      level: 12,
      avatar: 'MJ',
    },
    title: 'My journey from junior to senior developer',
    content: "Just hit my 5-year mark as a developer! Thought I'd share some insights and lessons learned along the way. Here's what I wish I knew when starting out...",
    category: 'Career',
    tags: ['Career', 'Tips'],
    likes: 87,
    replies: 23,
    timestamp: '5 hours ago',
  },
  {
    id: '3',
    author: {
      name: 'David Kim',
      level: 6,
      avatar: 'DK',
    },
    title: 'Built a real-time chat app with Socket.io!',
    content: "Finally completed my first real-time application! It's a chat app built with Node.js, Express, and Socket.io. Would love to get some feedback from the community.",
    category: 'Project Showcase',
    tags: ['Node.js', 'Socket.io'],
    likes: 45,
    replies: 12,
    timestamp: '1 day ago',
  },
];

export const todaysProblem: Problem = {
  id: 'today',
  title: 'Two Sum Problem',
  description: 'Given an array of integers and a target sum, return indices of two numbers that add up to the target.',
  difficulty: 'medium',
  category: 'Arrays',
  tags: ['Array', 'Hash Table'],
  xpReward: 500,
  completed: false,
  attempts: 0
};
